USE [master]
GO

/****** Object:  Database [HumanResources]    Script Date: 06-04-2020 12:46:50 ******/
CREATE DATABASE [HumanResources] ON  PRIMARY 
( NAME = N'HumanResources', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\HumanResources.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'HumanResources_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\HumanResources_log.LDF' , SIZE = 576KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [HumanResources] ADD FILEGROUP [FG0]
GO

ALTER DATABASE [HumanResources] ADD FILEGROUP [FG1]
GO

ALTER DATABASE [HumanResources] ADD FILEGROUP [FG2]
GO

ALTER DATABASE [HumanResources] ADD FILEGROUP [FG3]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HumanResources].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HumanResources] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HumanResources] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HumanResources] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HumanResources] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HumanResources] SET ARITHABORT OFF 
GO

ALTER DATABASE [HumanResources] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [HumanResources] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HumanResources] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HumanResources] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HumanResources] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HumanResources] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HumanResources] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HumanResources] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HumanResources] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HumanResources] SET  ENABLE_BROKER 
GO

ALTER DATABASE [HumanResources] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HumanResources] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HumanResources] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HumanResources] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HumanResources] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HumanResources] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HumanResources] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HumanResources] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HumanResources] SET  MULTI_USER 
GO

ALTER DATABASE [HumanResources] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HumanResources] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HumanResources] SET  READ_WRITE 
GO


